// AUTO-GENERATED by `cargo xtask gen-manifest` - DO NOT EDIT

/** Version of plugin packages (all @arborium/* packages share this version) */
export const pluginVersion = "2.0.0";

/** All available languages */
export const availableLanguages: string[] = [
  "agda",
  "commonlisp",
  "elixir",
  "elm",
  "erlang",
  "gleam",
  "haskell",
  "idris",
  "lean",
  "ocaml",
  "scheme",
];