name: CI Pipeline
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        run: |
          cargo build --release
          cargo test --all-features
          echo "Build complete!"
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          SECRET_KEY: ${{ secrets.DEPLOY_KEY }}
        run: ./deploy.sh
